pipeline{
    agent any
    stages  {
        stage('build') {
            steps {
                sh 'node --version'        
               
    stage('node') {
            steps {
                sh 'node --version'
            }
        }
    }
   }
  }
}
